[phases.setup]
nixPkgs = ["...", "openssl", "pkg-config", "protobuf"]
aptPkgs = ["libssl-dev", "protobuf-compiler"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/index-wallets-backend"