[phases.setup]
aptPkgs = ["protobuf-compiler", "libprotobuf-dev", "libssl-dev"]

[phases.build]
cmds = ["cargo build --release", "ls -la target/release/"]

[start]
cmd = "target/release/index_wallets_backend"